BEGIN;

CREATE TABLE lots
(
    id SMALLSERIAL PRIMARY KEY,
    name CHARACTER VARYING(30) NOT NULL,
	description CHARACTER VARYING(100) DEFAULT NULL
);

CREATE TABLE outcomes
(
	id BIGSERIAL PRIMARY KEY,
    value CHARACTER VARYING(30) NOT NULL,
	koef DECIMAL NOT NULL,
    lot_id BIGINT NOT NULL,
	FOREIGN KEY (lot_id) REFERENCES lots (id) ON DELETE CASCADE
);


COMMIT;